require("etrobert.remap")
require("etrobert.set")
require("etrobert.statusline")
require("etrobert.ask").setup()
require("etrobert.code-exec").setup()
require("etrobert.ai-rename").setup()
require("etrobert.bookmarks").setup()
