"Disables compatibility with vi
set nocompatible

"Prints line numbers
set number

"Updates the window title
set title

"Prints the cursor position
set ruler

"Sets syntaxing coloring
syntax on

"Prints a minimum of 3 lines around cursor
set scrolloff=3

if &term =~ '256color'
  " Disable Background Color Erase (BCE) so that color schemes
  " work properly when Vim is used inside tmux and GNU screen.
  set t_ut=
endif

"Set autoplete mode to zshlike
set wildmode=longest:full,full

"Visual autocomplete for command menu
set wildmenu

"Colors all matches on search
set hlsearch

"Search as characters are entered
set incsearch

"Specifies indentation behaviour for C like languages
"j1 adds support for lambda indentations (Java like)
"i-s sets the initialiser in constructors correctly
setlocal cindent cino=j1,(0,ws,Ws

"Allows backspacing over newlines, indents, start of insert
set backspace=eol,indent

"Changes the line numbers to be referent to current line
set rnu

"Highlight current line
set cursorline

"Set colorcolumn color to grey
highlight ColorColumn ctermbg=8

"Highlights the column 81
set colorcolumn=81

"Read scons files (SConstruct, SConscript) as python files
autocmd BufNewFile,BufRead SCons* set filetype=python

" build tags of your own project with Ctrl-F12
map <C-F12> :!ctags -R --sort=yes --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

"Set tabs width to 2
set shiftwidth=2
set tabstop=2
set softtabstop=2

"Set tabs width to 4 for Python files
autocmd FileType python setlocal shiftwidth=4 tabstop=4

"Autoexpands tabs
set expandtab

"Deactivates expandtab for makefiles
autocmd FileType make setlocal noexpandtab

"Enables dash (-) in C-n autocompletion
set iskeyword+=\-

" Refreshes GitGutter every 100ms
set updatetime=100

" Remove trailing whitespaces on save
autocmd BufWritePre,FileWritePre * %s/\s\+$//e

" Activate mouse for all modes
set mouse=a
