import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
size = 12
