if [[ $(uname) == Darwin ]]; then
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi

PROMPT_COMMAND='history -a'

stty -ixon
shopt -s globstar dotglob
bind '"\C-f": edit-and-execute-command'

HISTSIZE=
HISTFILESIZE=
