#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ $# -eq 0 ]; then
  echo "Usage: brightness-control [up|down]"
  exit 1
fi

# TODO: Fix multi-monitor support

DIRECTION=$1

EXPONENT=2
INCREMENT=2.5%

if [ "$DIRECTION" = "up" ]; then
  brightnessctl set --min-value=1 --exponent="$EXPONENT" "$INCREMENT+"
elif [ "$DIRECTION" = "down" ]; then
  brightnessctl set --min-value=1 --exponent="$EXPONENT" "$INCREMENT-"
fi

PERCENT=$(brightnessctl --exponent="$EXPONENT" -m | cut -d, -f4 | tr -d %)

notify-send -h int:value:"$PERCENT" \
  -h string:x-canonical-private-synchronous:brightness \
  "Brightness" "$PERCENT%"
