id: circadian_lighting
alias: "Circadian Lighting - Adjust lights throughout day"
description: "Gradually adjusts all lights based on sun elevation for circadian rhythm"
trigger:
  - platform: time_pattern
    minutes: "/15"  # Every 15 minutes
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: light.home
    state: "on"
action:
  - variables:
      min_elevation: -12
      max_elevation: 30
      min_brightness: 64
      max_brightness: 255
      min_color_temp: 250
      max_color_temp: 500
  - service: light.turn_on
    target:
      entity_id: light.home
    data:
      brightness: >
        {% set elevation = state_attr('sun.sun', 'elevation') | float %}
        {% set clamped = [min_elevation, [elevation, max_elevation] | min] | max %}
        {% set normalized = (clamped - min_elevation) / (max_elevation - min_elevation) %}
        {{ (min_brightness + (normalized * (max_brightness - min_brightness))) | int }}
      color_temp: >
        {% set elevation = state_attr('sun.sun', 'elevation') | float %}
        {% set clamped = [min_elevation, [elevation, max_elevation] | min] | max %}
        {% set normalized = (clamped - min_elevation) / (max_elevation - min_elevation) %}
        {{ (max_color_temp - (normalized * (max_color_temp - min_color_temp))) | int }}
      transition: 5  # 5 second smooth transition
mode: restart
