id: circadian_lighting
alias: "Circadian Lighting - Adjust lights throughout day"
description: "Gradually adjusts all lights based on time of day for circadian rhythm"
trigger:
  - platform: time_pattern
    minutes: "/15"  # Every 15 minutes
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: light.home
    state: "on"
action:
  - variables:
      min_time: 16
      max_time: 23
      min_brightness: 64
      max_brightness: 255
      min_color_temp: 250
      max_color_temp: 500
  - service: light.turn_on
    target:
      entity_id: light.home
    data:
      brightness: >
        {% set time = now().hour + (now().minute / 60.0) %}
        {% set clamped = [min_time, [time, max_time] | min] | max %}
        {% set normalized = (clamped - min_time) / (max_time - min_time) %}
        {{ (min_brightness + ((1 - normalized) * (max_brightness - min_brightness))) | int }}
      color_temp: >
        {% set time = now().hour + (now().minute / 60.0) %}
        {% set clamped = [min_time, [time, max_time] | min] | max %}
        {% set normalized = (clamped - min_time) / (max_time - min_time) %}
        {{ (max_color_temp - ((1 - normalized) * (max_color_temp - min_color_temp))) | int }}
      transition: 5  # 5 second smooth transition
mode: restart
