typeset -U path cdpath fpath manpath

# Use viins keymap as the default.
bindkey -v

setopt INTERACTIVE_COMMENTS

setopt APPEND_HISTORY
HISTSIZE="999999999"
SAVEHIST="999999999"

HISTFILE="$HOME/.zsh_history"

zmodload zsh/datetime

preexec() {
  if [[ -z $_cmd_start ]]; then
    _cmd_start=$EPOCHREALTIME
  fi
}

precmd() {
  if [[ -z $_cmd_start ]]; then
    return
  fi

  local _elapsed=$((EPOCHREALTIME * 1000 - _cmd_start * 1000))
  # Remove the decimal part to get the elapsed time in milliseconds as an integer
  export LAST_CMD_TIME=${_elapsed%%.*}
  unset _cmd_start
}

# compinit -i needed to avoid errors on mac
autoload -Uz compinit && compinit -i

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M viins "^F" edit-command-line
bindkey -M vicmd "^F" edit-command-line

bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char

# Override vi mode defaults: Ctrl-P/N for history search
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

bindkey -M viins "^A" beginning-of-line
bindkey -M vicmd "^A" beginning-of-line
bindkey -M viins "^E" end-of-line
bindkey -M vicmd "^E" end-of-line

bindkey -M vicmd '^U' vi-kill-line

bindkey "^Y" autosuggest-accept

# Moved here from profile because on darwin profile loads before agenix
[ -f /run/agenix/openai-api-key ] && export OPENAI_API_KEY="$(cat /run/agenix/openai-api-key)"
[ -f /run/agenix/gemini-api-key ] && export GEMINI_API_KEY="$(cat /run/agenix/gemini-api-key)"
