{ config, pkgs, ... }:
let
  symlink = path: config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/setup/${path}";

  albumArtWallpaper = pkgs.writeShellApplication {
    name = "album-art-wallpaper";
    runtimeInputs = with pkgs; [
      playerctl
      curl
      hyprland
    ];
    text = ''
      playerctl --follow metadata --format '{{mpris:artUrl}}' | while read -r url; do
        [ -z "$url" ] && continue
        curl -sL "$url" -o /tmp/albumart.jpg
        hyprctl hyprpaper wallpaper ",/tmp/albumart.jpg"
      done
    '';
  };
in
{
  imports = [ ./common.nix ];

  home.homeDirectory = "/home/${config.home.username}";

  home.sessionVariables.BROWSER = "firefox";

  home.file = {
    ".alias.linux".source = symlink "alias/.alias.linux";

    ".config/waybar/config.jsonc".source = symlink "waybar/.config/waybar/config.jsonc";
    ".config/waybar/style.css".source = symlink "waybar/.config/waybar/style.css";

    ".config/mako/config".source = ../../../mako/.config/mako/config;

    ".config/hypr/hyprland.conf".source = symlink "hyprland/.config/hypr/hyprland.conf";
    ".config/hypr/hyprpaper.conf".source = symlink "hyprland/.config/hypr/hyprpaper.conf";
    ".config/hypr/saint-levant.jpg".source = ../../../hyprland/.config/hypr/saint-levant.jpg;
  };

  # Ensures XDG_DATA_DIRS includes the profile share directory
  # so app launchers (wofi, rofi) can find .desktop files
  xdg.mime.enable = true;
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      # TODO: Check if this is necessary and if it doesn't default to browser anyway
      "video/mp4" = [ "firefox.desktop" ];
      "x-scheme-handler/sgnl" = [ "signal.desktop" ];
      "x-scheme-handler/signalcaptcha" = [ "signal.desktop" ];
    };
  };

  # Generated by claude
  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        hide_cursor = true;
        grace = 5;
      };
      auth = {
        "fingerprint:enabled" = true;
      };
      background = [
        {
          path = "screenshot";
          blur_passes = 3;
        }
      ];
      input-field = [
        {
          size = "200, 50";

          outer_color = "rgb(cdd6f4)";
          inner_color = "rgb(1e1e2e)";
          font_color = "rgb(cdd6f4)";

          placeholder_text = "";
          position = "0, -20";
        }
      ];
      label = [
        {
          text = "$TIME";
          font_family = "FiraCode Nerd Font";
          color = "rgb(cdd6f4)";
          font_size = 64;
          position = "0, 80"; # offset from center
        }
      ];
    };
  };

  services = {
    mpd = {
      enable = true;
      musicDirectory = "${config.home.homeDirectory}/sync/music";
      extraConfig = ''
        restore_paused "yes"
        auto_update "yes"

        audio_output {
          type "pipewire"
          name "PipeWire"
        }
      '';
    };

    mpdris2 = {
      enable = true;
      notifications = true;
    };

    hypridle = {
      enable = true;
      settings = {
        general = {
          lock_cmd = "pidof hyprlock || hyprlock";
          before_sleep_cmd = "loginctl lock-session";
        };
        listener = [
          {
            timeout = 300; # 5 minutes
            on-timeout = "loginctl lock-session";
          }
          {
            timeout = 900; # 15 minutes
            on-timeout = "systemctl suspend";
          }
        ];
      };
    };
  };

  systemd.user.services.album-art-wallpaper = {
    Unit.PartOf = [ "graphical-session.target" ];
    Service.ExecStart = "${albumArtWallpaper}/bin/album-art-wallpaper";
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
