#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

app_id=$1
title=$2

niri msg --json event-stream |
  jq --unbuffered --raw-output --arg app_id "$app_id" --arg title "$title" '
    .WindowOpenedOrChanged.window
    | select(.is_floating == false and (.app_id | test($app_id)) and (.title | test($title)))
    | .id
  ' |
  while read -r id; do
    niri msg action move-window-to-floating --id "$id"
  done
