#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

current_governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

if [ "$current_governor" = "performance" ]; then
  new_governor="powersave"
else
  new_governor="performance"
fi

cpupower frequency-set --governor=$new_governor
