name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Flake Check
        run: nix flake check ./nix --all-systems --accept-flake-config

  build:
    name: Build ${{ matrix.host }}
    runs-on: ${{ matrix.runner }}
    needs: check
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - host: tower
            runner: ubuntu-latest
            platform: nixos
          - host: leod
            runner: ubuntu-latest
            platform: nixos
          - host: pi
            runner: ubuntu-24.04-arm
            platform: nixos
          - host: aaron
            runner: macos-latest
            platform: darwin
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Build ${{ matrix.host }}
        run: |
          nix build ./nix#${{ matrix.platform }}Configurations.${{ matrix.host }}.config.system.build.toplevel \
            --accept-flake-config \
            --print-build-logs
